### ISSUE TITLE
New function: Add .obj/.mtl to a loaded scene

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/Spectacles.WebViewer#13]
Add a new function that loads an .obj/.mtl pair into the running scene.  Add the loaded object (I think it's actually a three.Group containing geometries) to a new layer called 'Obj Models' so they can be toggled on/off using the layers UI.

**Comment by anagpuyol** [comment]
this will be a great new feature!

**Comment by bhowes-tt** [comment]
Good to go!
