### ISSUE TITLE
Project splash page

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/Spectacles.WebViewer#21]
Spectacles needs a splash page, which will be hosted on the CORE studio website.  @mnaugle-tt wants to look into some fancy CSS and has some ideas about layout.

**Comment by mostaphaRoudsari** [comment]
This might be also a cool example. Very clean!

http://github.hubspot.com/pace/docs/welcome/

**Comment by anagpuyol** [comment]
I am looking into something like this for the VR page

http://www.fiftythree.com/

You can scroll down and get the projects to visualize

**Comment by mnaugle-tt** [comment]
@mostaphaRoudsari --

Looking at mocking up two different single pages.  One that utilizes bootstraps similar to something like this: http://ironsummitmedia.github.io/startbootstrap-freelancer/ 

And one full width, single click scroll page similar to modelo.io or this: http://alvarotrigo.com/fullPage/#secondPage

Too torn on which one to go with, so I will try both and we can vote on which we like better!
The bootstrap page does better with grids of images / thumbnails, the sleek single click scroll ones don't do as well with resizing for mobile, but look super cool.
